### PR TITLE
NodeJS version change

### PR DESCRIPTION
**Pull request by DunkieGaming**
## Problem

- Uptime Karma fails to install with NodeJS 20 because of a memory leak error

## Solution

- Changed nodejs_version=20 to nodejs_version=18 in scripts/_common.sh

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by DunkieGaming** [comment]
!testme

**Comment by orhtej2** [comment]
Test update from previous version, if the `upgrade ` script does not fully replace `node_modules` the app will likely fail to start.

**Comment by ketsapiwiq** [comment]
!testme

**Comment by ketsapiwiq** [comment]
Mmmh but I don't understand the root of this memory leak issue, it does work fine on other people's install. I don't see why it shouldn't be merged tho, provided the upgrade to this node v18 version does indeed work.

**Pull request merged**
